let allPlaces=[],places=[],index=0,liked=[],activeFilter='all',activeArea='all',isAnimating=false,favoritesFirst=false,nearMeMode=false,userLocation=null;
const deck=document.getElementById('deck'),fill=document.getElementById('fill'),progressText=document.getElementById('progressText'),count=document.getElementById('count');
const favorites=new Set(JSON.parse(localStorage.getItem('lekisFavorites')||'[]'));
const photoCache=JSON.parse(localStorage.getItem('lekisPhotoCacheV2')||'{}');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const artFor=p=>`linear-gradient(145deg,${p.colors?.[0]||'#84a878'},${p.colors?.[1]||'#d9e2bc'})`;
const mapQuery=p=>encodeURIComponent(p.mapQuery||`${p.name}, ${p.area}, Stockholm`);
const isFav=p=>favorites.has(p.id);
const areaCenters={'Aspudden':[59.306,18.001],'Bandhagen':[59.270,18.050],'Södermalm':[59.314,18.072],'Järvastaden':[59.389,17.999],'Vasastan':[59.343,18.047],'Östermalm':[59.338,18.086],'Kungsholmen':[59.333,18.031],'Gärdet':[59.344,18.103],'Tantolunden':[59.312,18.044],'Solberga':[59.297,17.995],'Fruängen':[59.286,17.965],'Hökarängen':[59.257,18.084],'Gubbängen':[59.263,18.083],'Midsommarkransen':[59.301,18.000],'Fredhäll':[59.331,18.007],'Norra Djurgården':[59.367,18.116],'Akalla':[59.414,17.913],'Hammarby Sjöstad':[59.302,18.104],'Hägersten':[59.302,17.985],'Älvsjö':[59.279,18.009],'Skärholmen':[59.276,17.907],'Bredäng':[59.295,17.934],'Vällingby':[59.363,17.873],'Blackeberg':[59.348,17.882],'Bromma':[59.338,17.939],'Årsta':[59.297,18.051],'Enskede':[59.280,18.070],'Farsta':[59.243,18.091],'Hammarbyhöjden':[59.294,18.104],'Bagarmossen':[59.277,18.132],'Skarpnäck':[59.267,18.134],'Kärrtorp':[59.284,18.115],'Husby':[59.410,17.925],'Rinkeby':[59.389,17.928],'Tensta':[59.394,17.902],'Spånga':[59.382,17.897]};
function saveFavorites(){localStorage.setItem('lekisFavorites',JSON.stringify([...favorites]))}
function normalizePhotoResult(page){const ii=page?.imageinfo?.[0];if(!ii?.thumburl&&!ii?.url)return null;return {url:ii.thumburl||ii.url,source:page.fullurl||`https://commons.wikimedia.org/?curid=${page.pageid}`,title:page.title||''}}
function photoScore(hit,p){const t=(hit.title||'').toLowerCase(),name=p.name.toLowerCase().replace(/parkleken|parklek|lekplats|plaskdamm|4h-gård/g,'').trim(),area=(p.area||'').toLowerCase();let s=0;for(const token of name.split(/\s+/).filter(x=>x.length>3)){if(t.includes(token))s+=3}if(area&&t.includes(area))s+=2;if(t.includes('park'))s+=1;return s}
async function commonsSearch(term,p){const url='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrlimit=12&prop=imageinfo|info&iiprop=url&iiurlwidth=1200&inprop=url&format=json&origin=*&gsrsearch='+encodeURIComponent(term);const j=await fetch(url).then(r=>r.json());return Object.values(j.query?.pages||{}).map(normalizePhotoResult).filter(Boolean).sort((a,b)=>photoScore(b,p)-photoScore(a,p))}
async function findPhoto(p){if(photoCache[p.id])return photoCache[p.id];const plain=p.name.replace(/Parkleken|parklek|lekplats|plaskdamm/gi,'').trim();const terms=[p.name,`${plain} Stockholm`,`${plain} ${p.area}`,`${p.area} lekpark Stockholm`];for(const term of terms){try{const hits=await commonsSearch(term,p);const best=hits.find(h=>photoScore(h,p)>=3)||hits[0];if(best){photoCache[p.id]=best;try{localStorage.setItem('lekisPhotoCacheV2',JSON.stringify(photoCache))}catch{}return best}}catch{}}return null}
function setArtPhoto(el,p,photo){if(!el)return;el.style.backgroundImage=photo?`linear-gradient(180deg,transparent 30%,rgba(0,0,0,.68)),url("${photo.url}")`:artFor(p);el.classList.toggle('hasPhoto',!!photo)}
async function hydrateCardPhotos(){const arts=[...deck.querySelectorAll('.art[data-place-id]')];await Promise.all(arts.map(async art=>{const p=allPlaces.find(x=>x.id===art.dataset.placeId);if(!p)return;const photo=await findPhoto(p);if(document.body.contains(art)&&photo)setArtPhoto(art,p,photo)}))}
function favButtonHTML(p){return `<button class="cardFav ${isFav(p)?'active':''}" data-fav-id="${esc(p.id)}" aria-label="Favorit">${isFav(p)?'★':'☆'}</button>`}
function cardHTML(p,b=false){return `<article class="card ${b?'behind':'front'}"><div class="stamp no">PASS</div><div class="stamp yes">SPARA</div><div class="art" data-place-id="${esc(p.id)}" style="background-image:${artFor(p)}"><div class="typePill">${esc(p.type.toUpperCase())}</div>${favButtonHTML(p)}<div class="artCopy"><h1>${esc(p.name)}</h1><p>${esc(p.area)}</p></div></div><div class="cardBody"><p class="desc">${esc(p.summary)}</p><div class="chips">${(p.tags||[]).slice(0,3).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><button class="more">MER INFO →</button></div></article>`}
function bindCardButtons(c,p){c.querySelector('.more').onclick=e=>{e.stopPropagation();openDetails(p)};c.querySelector('.cardFav').onclick=e=>{e.stopPropagation();toggleFavorite(p);render()}}
function render(){isAnimating=false;count.textContent=liked.length;if(index>=places.length){deck.innerHTML=`<div class="empty"><div style="font-size:42px">🛝</div><h2>Klart!</h2><p>Du sparade ${liked.length} ställen.</p><button class="primary" onclick="openSaved()">SE SPARADE STÄLLEN</button></div>`;progressText.textContent=`${places.length} / ${places.length}`;fill.style.width='100%';return}deck.innerHTML=(places[index+1]?cardHTML(places[index+1],true):'')+cardHTML(places[index]);progressText.textContent=`${index+1} / ${places.length}`;fill.style.width=`${places.length?index/places.length*100:0}%`;const c=deck.querySelector('.front');bindSwipe(c);bindCardButtons(c,places[index]);const behind=deck.querySelector('.behind');if(behind&&places[index+1])bindCardButtons(behind,places[index+1]);hydrateCardPhotos()}
function bindSwipe(card){let pointerId=null,sx=0,sy=0,x=0,y=0,drag=false,raf=0;const yes=card.querySelector('.yes'),no=card.querySelector('.no'),behind=deck.querySelector('.behind');const paint=()=>{raf=0;const p=Math.min(Math.abs(x)/110,1);card.style.transform=`translate3d(${x}px,${y*.06}px,0) rotate(${Math.max(-8,Math.min(8,x/28))}deg)`;if(x>0){yes.style.opacity=p;no.style.opacity=0}else{no.style.opacity=p;yes.style.opacity=0}if(behind)behind.style.transform=`translateY(${9-7*p}px) scale(${.97+.03*p})`};card.onpointerdown=e=>{if(isAnimating||e.target.closest('.more,.cardFav'))return;pointerId=e.pointerId;drag=true;sx=e.clientX;sy=e.clientY;x=y=0;card.classList.add('dragging');try{card.setPointerCapture(pointerId)}catch{}};card.onpointermove=e=>{if(!drag||e.pointerId!==pointerId)return;x=e.clientX-sx;y=e.clientY-sy;if(!raf)raf=requestAnimationFrame(paint)};const end=e=>{if(!drag||e.pointerId!==pointerId)return;drag=false;card.classList.remove('dragging');try{card.releasePointerCapture(pointerId)}catch{}if(Math.abs(x)>78){decide(x>0?'like':'pass',card,Math.sign(x))}else{card.style.transform='';yes.style.opacity=no.style.opacity=0;if(behind)behind.style.transform='';x=y=0}};card.onpointerup=end;card.onpointercancel=end}
function decide(type,card=deck.querySelector('.front'),dir=type==='like'?1:-1){if(isAnimating||!card||index>=places.length)return;isAnimating=true;const p=places[index];if(type==='like'&&!liked.some(x=>x.id===p.id))liked.push(p);count.textContent=liked.length;card.classList.add('leaving');card.style.transform=`translate3d(${dir*Math.max(innerWidth,560)*1.3}px,-12px,0) rotate(${dir*12}deg)`;card.style.opacity='0';window.dispatchEvent(new CustomEvent('lekis:swipe',{detail:{place:p,liked:type==='like'}}));setTimeout(()=>{index++;render()},210)}
passBtn.onclick=()=>decide('pass');likeBtn.onclick=()=>decide('like');
function toggleFavorite(p){if(isFav(p))favorites.delete(p.id);else favorites.add(p.id);saveFavorites();detailFavBtn.textContent=isFav(p)?'★ FAVORIT':'☆ FAVORIT';detailFavBtn.classList.toggle('active',isFav(p));if(favoritesFirst)rebuildPlaces(false)}
async function openDetails(p){detailArt.style.backgroundImage=artFor(p);detailArt.classList.remove('hasPhoto');detailArt.innerHTML='<div class="photoLoading">HÄMTAR PLATSBILD…</div>';detailType.textContent=`${p.type.toUpperCase()} · ${p.area}`;detailTitle.textContent=p.name;detailText.textContent=p.summary;detailChips.innerHTML=(p.tags||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('');detailFavBtn.textContent=isFav(p)?'★ FAVORIT':'☆ FAVORIT';detailFavBtn.classList.toggle('active',isFav(p));detailFavBtn.onclick=()=>toggleFavorite(p);detailRows.innerHTML=`<div class="detailRow"><b>PASSAR BÄST</b><span>${esc(p.bestFor)}</span></div><div class="detailRow"><b>KÄNSLA</b><span>${esc(p.vibe)}</span></div><div class="detailRow"><b>FINNS HÄR</b><span>${esc((p.features||[]).join(' · '))}</span></div>${p.address?`<div class="detailRow"><b>ADRESS</b><span>${esc(p.address)}</span></div>`:''}<div class="mapWrap"><iframe title="Karta över ${esc(p.name)}" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=${mapQuery(p)}&output=embed"></iframe></div><a class="mapLink" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${mapQuery(p)}">ÖPPNA I KARTOR →</a>`;details.classList.add('show');const photo=await findPhoto(p);if(!details.classList.contains('show'))return;detailArt.innerHTML='';setArtPhoto(detailArt,p,photo);if(photo){const a=document.createElement('a');a.className='photoCredit';a.href=photo.source;a.target='_blank';a.rel='noopener';a.textContent='Foto: Wikimedia Commons';detailArt.appendChild(a)}else{detailArt.innerHTML='<div class="photoLoading">INGEN FRI PLATSBILD HITTADES</div>'}}
closeDetails.onclick=()=>details.classList.remove('show');
function openSaved(){const arr=[...liked].sort((a,b)=>Number(isFav(b))-Number(isFav(a)));savedList.innerHTML=arr.length?arr.map(p=>`<div class="placeSaved"><button class="savedFav ${isFav(p)?'active':''}" data-saved-fav="${esc(p.id)}">${isFav(p)?'★':'☆'}</button><div><b>${esc(p.name)}</b><span>${esc(p.area)} · ${esc(p.type)}</span></div><button class="savedInfo" data-saved-info="${esc(p.id)}">MER INFO</button></div>`).join(''):'<div class="empty">Inga sparade ställen ännu.</div>';savedList.querySelectorAll('[data-saved-fav]').forEach(b=>b.onclick=()=>{const p=allPlaces.find(x=>x.id===b.dataset.savedFav);if(p){toggleFavorite(p);openSaved()}});savedList.querySelectorAll('[data-saved-info]').forEach(b=>b.onclick=()=>{const p=allPlaces.find(x=>x.id===b.dataset.savedInfo);if(p){savedSheet.classList.remove('show');openDetails(p)}});savedSheet.classList.add('show')}
savedBtn.onclick=openSaved;closeSaved.onclick=()=>savedSheet.classList.remove('show');resetBtn.onclick=()=>{liked=[];index=0;rebuildPlaces();savedSheet.classList.remove('show')};
function haversine(a,b){const R=6371,rad=x=>x*Math.PI/180,dLat=rad(b[0]-a[0]),dLon=rad(b[1]-a[1]),x=Math.sin(dLat/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function placeDistance(p){const c=areaCenters[p.area]||[59.3293,18.0686];return userLocation?haversine(userLocation,c):999}
function rebuildPlaces(resetIndex=true){let next=activeFilter==='all'?[...allPlaces]:allPlaces.filter(p=>p.type===activeFilter);if(activeArea!=='all'&&!nearMeMode)next=next.filter(p=>p.area===activeArea);if(nearMeMode&&userLocation)next.sort((a,b)=>placeDistance(a)-placeDistance(b));if(favoritesFirst)next.sort((a,b)=>Number(isFav(b))-Number(isFav(a)));places=next;if(resetIndex)index=0;isAnimating=false;render();window.dispatchEvent(new CustomEvent('lekis:poolchange'))}
function applyFilter(f){activeFilter=f;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));rebuildPlaces()}
filters.onclick=e=>{const b=e.target.closest('.filter');if(b){activeFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b))}};
function updateBrowseLabel(){browseLabel.textContent=nearMeMode?'Nära mig':activeArea==='all'?'Hela Stockholm':activeArea}
browseBtn.onclick=()=>browseSheet.classList.add('show');closeBrowse.onclick=()=>browseSheet.classList.remove('show');
areaSelect.onchange=()=>{activeArea=areaSelect.value;nearMeMode=false;nearMeBtn.classList.remove('active');updateBrowseLabel()};
nearMeBtn.onclick=()=>{nearMeBtn.classList.add('loading');nearMeBtn.querySelector('small').textContent='Hämtar din position…';if(!navigator.geolocation){alert('Din webbläsare stödjer inte platsdelning.');nearMeBtn.classList.remove('loading');return}navigator.geolocation.getCurrentPosition(pos=>{userLocation=[pos.coords.latitude,pos.coords.longitude];nearMeMode=true;activeArea='all';areaSelect.value='all';nearMeBtn.classList.remove('loading');nearMeBtn.classList.add('active');nearMeBtn.querySelector('small').textContent='Klart — närmaste områden visas först';updateBrowseLabel()},()=>{nearMeBtn.classList.remove('loading');nearMeBtn.querySelector('small').textContent='Kunde inte använda din position';alert('Tillåt platsåtkomst för Lekis i webbläsaren för att använda Nära mig.')},{enableHighAccuracy:false,timeout:8000,maximumAge:300000})};
applyBrowse.onclick=()=>{rebuildPlaces();browseSheet.classList.remove('show')};
favFirstBtn.onclick=()=>{favoritesFirst=!favoritesFirst;favFirstBtn.classList.toggle('active',favoritesFirst);favFirstBtn.setAttribute('aria-pressed',String(favoritesFirst));favFirstBtn.textContent=favoritesFirst?'★':'☆';rebuildPlaces()};
function populateAreas(){const areas=[...new Set(allPlaces.map(p=>p.area).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'sv'));areaSelect.innerHTML='<option value="all">Hela Stockholm</option>'+areas.map(a=>`<option value="${esc(a)}">${esc(a)}</option>`).join('')}
function showOnboarding(force=false){if(force||!localStorage.getItem('lekisOnboarded'))onboarding.classList.add('show')}
function closeOnboarding(){localStorage.setItem('lekisOnboarded','1');onboarding.classList.remove('show')}
startBtn.onclick=closeOnboarding;helpLink.onclick=()=>{browseSheet.classList.remove('show');showOnboarding(true)};
window.LEKIS={get places(){return places},get allPlaces(){return allPlaces},get index(){return index},set index(v){index=v},get liked(){return liked},set liked(v){liked=v},render,applyFilter,esc,rebuildPlaces};
fetch('./places.json',{cache:'no-store'}).then(r=>r.json()).then(d=>{allPlaces=d;populateAreas();rebuildPlaces();showOnboarding()}).catch(()=>{deck.innerHTML='<div class="empty">Kunde inte ladda ställen.</div>'});