let allPlaces=[],places=[],index=0,liked=[],activeFilter='all';
const deck=document.getElementById('deck'),fill=document.getElementById('fill'),progressText=document.getElementById('progressText'),count=document.getElementById('count');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const artFor=p=>`linear-gradient(145deg,${p.colors?.[0]||'#84a878'},${p.colors?.[1]||'#d9e2bc'})`;
function cardHTML(p,b=false){return `<article class="card ${b?'behind':'front'}"><div class="stamp no">PASS</div><div class="stamp yes">LEKA</div><div class="art" style="--art:${artFor(p)}"><div class="typePill">${esc(p.type.toUpperCase())}</div><div class="artCopy"><h1>${esc(p.name)}</h1><p>${esc(p.area)}</p></div></div><div class="cardBody"><p class="desc">${esc(p.summary)}</p><div class="chips">${(p.tags||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><button class="more">MER INFO →</button></div></article>`}
function render(){count.textContent=liked.length;if(index>=places.length){deck.innerHTML=`<div class="empty"><div style="font-size:42px">🛝</div><h2>Klart!</h2><p>Du sparade ${liked.length} ställen.</p><button class="primary" onclick="openSaved()">SE MINA STÄLLEN</button></div>`;progressText.textContent=`${places.length} / ${places.length}`;fill.style.width='100%';return}deck.innerHTML=(places[index+1]?cardHTML(places[index+1],true):'')+cardHTML(places[index]);progressText.textContent=`${index+1} / ${places.length}`;fill.style.width=`${index/places.length*100}%`;const c=deck.querySelector('.front');bindSwipe(c);c.querySelector('.more').onclick=e=>{e.stopPropagation();openDetails(places[index])}}
function bindSwipe(card){let id=null,sx=0,x=0,y=0,drag=false;const yes=card.querySelector('.yes'),no=card.querySelector('.no'),behind=deck.querySelector('.behind');const paint=()=>{const p=Math.min(Math.abs(x)/110,1);card.style.transform=`translate3d(${x}px,${y*.04}px,0) rotate(${Math.max(-8,Math.min(8,x/28))}deg)`;if(x>0){yes.style.opacity=p;no.style.opacity=0}else{no.style.opacity=p;yes.style.opacity=0}if(behind)behind.style.transform=`translateY(${9-7*p}px) scale(${.97+.03*p})`};card.onpointerdown=e=>{if(e.target.closest('.more'))return;id=e.pointerId;drag=true;sx=e.clientX;card.classList.add('dragging');card.setPointerCapture?.(id)};card.onpointermove=e=>{if(!drag||e.pointerId!==id)return;x=e.clientX-sx;y=e.clientY;paint()};const end=e=>{if(!drag||e.pointerId!==id)return;drag=false;card.classList.remove('dragging');if(Math.abs(x)>78)decide(x>0?'like':'pass',card,Math.sign(x));else{card.style.transform='';yes.style.opacity=no.style.opacity=0;if(behind)behind.style.transform='';x=y=0}};card.onpointerup=end;card.onpointercancel=end}
function decide(type,card=deck.querySelector('.front'),dir=type==='like'?1:-1){if(!card||index>=places.length)return;const p=places[index];if(type==='like'&&!liked.some(x=>x.id===p.id))liked.push(p);count.textContent=liked.length;card.classList.add('leaving');card.style.transform=`translate3d(${dir*Math.max(innerWidth,560)*1.3}px,-12px,0) rotate(${dir*12}deg)`;card.style.opacity='0';setTimeout(()=>{index++;render()},190);window.dispatchEvent(new CustomEvent('lekis:swipe',{detail:{place:p,liked:type==='like'}}))}
passBtn.onclick=()=>decide('pass');likeBtn.onclick=()=>decide('like');
function openDetails(p){detailArt.style.setProperty('--art',artFor(p));detailType.textContent=`${p.type.toUpperCase()} · ${p.area}`;detailTitle.textContent=p.name;detailText.textContent=p.summary;detailChips.innerHTML=(p.tags||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('');detailRows.innerHTML=`<div class="detailRow"><b>PASSAR BÄST</b><span>${esc(p.bestFor)}</span></div><div class="detailRow"><b>KÄNSLA</b><span>${esc(p.vibe)}</span></div><div class="detailRow"><b>FINNS HÄR</b><span>${esc((p.features||[]).join(' · '))}</span></div>`;details.classList.add('show')}
closeDetails.onclick=()=>details.classList.remove('show');
function openSaved(){savedList.innerHTML=liked.length?liked.map(p=>`<div class="placeSaved"><b>${esc(p.name)}</b><span>${esc(p.area)} · ${esc(p.type)}</span></div>`).join(''):'<div class="empty">Inga sparade ställen ännu.</div>';savedSheet.classList.add('show')}
savedBtn.onclick=openSaved;closeSaved.onclick=()=>savedSheet.classList.remove('show');resetBtn.onclick=()=>{liked=[];index=0;applyFilter(activeFilter);savedSheet.classList.remove('show')};
function applyFilter(f){activeFilter=f;places=f==='all'?[...allPlaces]:allPlaces.filter(p=>p.type===f);index=0;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));render();window.dispatchEvent(new CustomEvent('lekis:poolchange'))}
filters.onclick=e=>{const b=e.target.closest('.filter');if(b)applyFilter(b.dataset.filter)};
window.LEKIS={get places(){return places},get allPlaces(){return allPlaces},get index(){return index},set index(v){index=v},get liked(){return liked},set liked(v){liked=v},render,applyFilter,esc};
fetch('./places.json',{cache:'no-store'}).then(r=>r.json()).then(d=>{allPlaces=d;places=[...d];render()}).catch(()=>{deck.innerHTML='<div class="empty">Kunde inte ladda ställen.</div>'});