let duoInvite=null;
function enc(o){const b=new TextEncoder().encode(JSON.stringify(o));let s='';b.forEach(x=>s+=String.fromCharCode(x));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function dec(s){try{const b=s.replace(/-/g,'+').replace(/_/g,'/');const p=b+'='.repeat((4-b.length%4)%4);return JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(p),c=>c.charCodeAt(0))))}catch{return null}}
function duoName(){const old=localStorage.getItem('lekisName')||'';const n=prompt('Vad heter du?',old)||'';if(n.trim())localStorage.setItem('lekisName',n.trim());return n.trim()}
async function shareLink(url,text){try{if(navigator.share)await navigator.share({title:'Lekis Duo',text,url});else if(navigator.clipboard){await navigator.clipboard.writeText(url);alert('Länken är kopierad!')}else prompt('Kopiera länken:',url)}catch{}}
function renderDuoHome(){duoBody.innerHTML=`<p>Swipa dina ställen först. Skicka sedan en Duo-länk till en annan förälder som swipar samma lista.</p><button class="primary" id="makeDuo">SKAPA DUO FRÅN MINA VAL</button>`;document.getElementById('makeDuo').onclick=createDuoInvite}
function createDuoInvite(){const name=duoName();if(!name)return;const data={v:1,a:{name,choices:liked.map(p=>p.id)}};const url=location.origin+location.pathname+'#duo='+enc(data);shareLink(url,`${name} vill hitta ett ställe att ses med barnen. Swipa samma Lekis-lista och se var ni matchar.`)}
function showDuoResult(){if(!duoInvite)return;const name=duoName()||'Du';const mine=new Set(liked.map(p=>p.id)),theirs=new Set(duoInvite.a.choices||[]);const both=allPlaces.filter(p=>mine.has(p.id)&&theirs.has(p.id));const onlyA=allPlaces.filter(p=>theirs.has(p.id)&&!mine.has(p.id));const onlyB=allPlaces.filter(p=>mine.has(p.id)&&!theirs.has(p.id));duoBody.innerHTML=`<p><b>${LEKIS.esc(duoInvite.a.name)} × ${LEKIS.esc(name)}</b></p><div class="eyebrow">BÅDA GILLAR · ${both.length}</div>${both.map(p=>`<div class="placeSaved"><b>${LEKIS.esc(p.name)}</b><span>${LEKIS.esc(p.area)}</span></div>`).join('')||'<div class="empty">Ingen gemensam träff ännu.</div>'}<div class="eyebrow" style="margin-top:20px">BARA ${LEKIS.esc(duoInvite.a.name.toUpperCase())} · ${onlyA.length}</div>${onlyA.map(p=>`<div class="placeSaved"><b>${LEKIS.esc(p.name)}</b><span>${LEKIS.esc(p.area)}</span></div>`).join('')}<div class="eyebrow" style="margin-top:20px">BARA ${LEKIS.esc(name.toUpperCase())} · ${onlyB.length}</div>${onlyB.map(p=>`<div class="placeSaved"><b>${LEKIS.esc(p.name)}</b><span>${LEKIS.esc(p.area)}</span></div>`).join('')}`;duoSheet.classList.add('show')}
function openDuo(){if(duoInvite&&index>=places.length)showDuoResult();else if(duoInvite){duoBody.innerHTML=`<p><b>${LEKIS.esc(duoInvite.a.name)}</b> har skickat en Duo till dig. Swipa klart listan först, så visas era gemensamma ställen här.</p>`}else renderDuoHome();duoSheet.classList.add('show')}
duoBtn.onclick=openDuo;closeDuo.onclick=()=>duoSheet.classList.remove('show');
const m=location.hash.match(/^#duo=(.+)$/);if(m){duoInvite=dec(m[1]);duoBtn.textContent='DUO · AKTIV'}
window.addEventListener('lekis:swipe',()=>{if(duoInvite&&index>=places.length-1)setTimeout(showDuoResult,240)});