const LEKIS_GROUP_URL='https://vhoaliujkgnnmmzdfdbi.supabase.co/rest/v1/rpc/';
const LEKIS_GROUP_KEY='sb_publishable_eS90uE7LZC7T4nkuvYLdxQ_TuZFt6zy';
let groupRoom=null,groupState=null,groupPoll=null,groupCatalog=[];
function groupRPC(fn,body){return fetch(LEKIS_GROUP_URL+fn,{method:'POST',headers:{'Content-Type':'application/json','apikey':LEKIS_GROUP_KEY,'Authorization':'Bearer '+LEKIS_GROUP_KEY},body:JSON.stringify(body)}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.message||j.error||'Gruppfel');return j})}
function roomKey(code){return 'lekis-group-'+String(code||'').toUpperCase()}
function groupName(){const old=localStorage.getItem('lekisName')||'';const n=prompt('Vad heter du?',old)||'';if(n.trim())localStorage.setItem('lekisName',n.trim());return n.trim()}
async function shareLink(url,text){try{if(navigator.share)await navigator.share({title:'Lekis Grupp',text,url});else if(navigator.clipboard){await navigator.clipboard.writeText(url);alert('Länken är kopierad!')}else prompt('Kopiera länken:',url)}catch{}}
function poolForRoom(){return (groupCatalog.length?groupCatalog:LEKIS.allPlaces).map(p=>({id:p.id,title:p.name}))}
async function createGroup(){const name=groupName();if(!name)return;if(!groupCatalog.length)groupCatalog=[...LEKIS.allPlaces];const res=await groupRPC('lekis_group_create',{p_name:name,p_pool:poolForRoom()});groupRoom={code:res.code,token:res.token,name:res.name};localStorage.setItem(roomKey(res.code),JSON.stringify(groupRoom));location.hash='group='+res.code;await activateGroup();await shareGroup()}
async function joinGroup(code){const saved=localStorage.getItem(roomKey(code));if(saved){groupRoom=JSON.parse(saved);return activateGroup()}const name=groupName();if(!name)return;const res=await groupRPC('lekis_group_join',{p_code:code,p_name:name});groupRoom={code:res.code,token:res.token,name:res.name};localStorage.setItem(roomKey(res.code),JSON.stringify(groupRoom));await activateGroup()}
async function shareGroup(){if(!groupRoom)return;const url=location.origin+location.pathname+'#group='+groupRoom.code;await shareLink(url,`${groupRoom.name} vill hitta ett barnhäng med dig. Gå med i Lekis-gruppen och swipa samma ställen.`)}
async function loadGroupState(){if(!groupRoom)return null;groupState=await groupRPC('lekis_group_state',{p_code:groupRoom.code,p_token:groupRoom.token});renderGroupBody();return groupState}
async function waitForPlaces(){return new Promise(resolve=>{const t=setInterval(()=>{if(LEKIS.allPlaces.length){clearInterval(t);resolve()}},60)})}
async function activateGroup(){await waitForPlaces();if(!groupCatalog.length)groupCatalog=[...LEKIS.allPlaces];const s=await loadGroupState();const done=new Set(s.swiped||[]);LEKIS.applyFilter('all');const remaining=groupCatalog.filter(p=>!done.has(p.id));places=remaining;index=0;liked=[];LEKIS.render();clearInterval(groupPoll);groupPoll=setInterval(()=>loadGroupState().catch(()=>{}),2500);duoBtn.textContent=`GRUPP · ${s.members.length}`}
function placeById(id){return (groupCatalog.length?groupCatalog:LEKIS.allPlaces).find(p=>p.id===id)}
function topResults(){const memberCount=groupState?.members?.length||0;const rows=(groupState?.scores||[]).map(x=>({...x,place:placeById(x.id)})).filter(x=>x.place).sort((a,b)=>b.likes-a.likes);return rows.map(x=>`<div class="placeSaved"><b>${LEKIS.esc(x.place.name)}</b><span>${x.likes} av ${memberCount} gillar · ${LEKIS.esc(x.place.area)}</span></div>`).join('')||'<div class="empty">Inga gemensamma likes ännu.</div>'}
function renderGroupBody(){if(!groupRoom){duoBody.innerHTML=`<p>Starta en grupp och bjud in upp till åtta föräldrar. Alla swipar samma ställen och ni ser vilka platser flest gillar.</p><button class="primary" id="makeGroup">SKAPA GRUPP</button>`;document.getElementById('makeGroup').onclick=()=>createGroup().catch(e=>alert(e.message));return}const members=groupState?.members||[];duoBody.innerHTML=`<p><b>${LEKIS.esc(groupRoom.name)}</b> · gruppkod</p><div class="duoCode">${LEKIS.esc(groupRoom.code)}</div><div class="duoMembers">${members.map(m=>`${m.isMe?'●':'○'} ${LEKIS.esc(m.name)} · ${m.swiped}/${m.total}`).join('<br>')}</div><button class="primary" id="shareGroup">BJUD IN FLER</button><div class="eyebrow" style="margin-top:24px">TOPP JUST NU</div>${topResults()}<button class="secondary" id="leaveGroup">LÄMNA GRUPP</button>`;document.getElementById('shareGroup').onclick=shareGroup;document.getElementById('leaveGroup').onclick=leaveGroup;duoBtn.textContent=`GRUPP · ${members.length}`}
function openGroup(){renderGroupBody();duoSheet.classList.add('show')}
function leaveGroup(){clearInterval(groupPoll);groupPoll=null;groupRoom=null;groupState=null;location.hash='';location.reload()}
duoBtn.onclick=openGroup;closeDuo.onclick=()=>duoSheet.classList.remove('show');matchContinue.onclick=()=>matchToast.classList.remove('show');
window.addEventListener('lekis:swipe',e=>{if(!groupRoom)return;const p=e.detail.place;groupRPC('lekis_group_swipe',{p_code:groupRoom.code,p_token:groupRoom.token,p_place_id:p.id,p_liked:e.detail.liked}).then(res=>{if(res.unanimous&&res.members>1){matchTitle.textContent=p.name;matchToast.classList.add('show')}return loadGroupState()}).catch(()=>{})});
window.addEventListener('lekis:poolchange',()=>{if(groupRoom&&groupCatalog.length){places=groupCatalog;index=0;liked=[];LEKIS.render()}});
const gm=location.hash.match(/^#group=([A-Za-z0-9]+)/);if(gm)waitForPlaces().then(()=>joinGroup(gm[1].toUpperCase()).catch(e=>alert(e.message)));else renderGroupBody();